env:
    es6: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2018
    sourceType: module
rules:
    indent:
        - error
        - 2
    linebreak-style:
        - 0
        - error
        - windows
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console: off
    no-inner-declarations: off
    '@typescript-eslint/no-explicit-any': off
    # TODO: Clean-up code and enable following rules
    '@typescript-eslint/camelcase': off
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-use-before-define': off
    '@typescript-eslint/ban-ts-comment': off
globals:
    window: true
    fetch: true
    Headers: true
    document: true

