language: node_js

node_js:
    - stable
    - 14
    - 15

branches:
    only:
        - master

env:
    - NODE_ENV=ci
    - NODE_ENV=ci-betanet
    #  - NODE_ENV=betanet

cache: yarn


jobs:
    allow_failures:
        - stage: Produce Coverage
    include:
        - name: yarn
          script:
              - yarn lint
              - yarn test
              - yarn browserify && yarn run bundlewatch

        - name: fossa
          before_script:
              - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/fc60c6631a5d372d5a45fea35e31665b338f260d/install.sh | sudo bash"
          script:
              - fossa init
              - fossa analyze --server-scan
              - fossa test
        - name: danger
          script:
              - yarn danger ci

        - stage: Produce Coverage
            node_js: stable
            script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
