# This workflow builds the docs and deploys them to GitHub Pages on every commit to the master branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Build & Deploy Docs"

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Install & Build Docs 🔧
              uses: actions/setup-node@v1
              with:
                node-version: '15.x'
            - run: yarn install --frozen-lockfile && yarn doc

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                git-config-name: gh-workflow
                git-config-email: gh-workflow@github.com
                token: ${{ secrets.ACCESS_TOKEN }}
                branch: gh-pages
                folder: docs
                single-commit: true
                clean: true
                silent: true

#            - name: Cleanup Generated Branch
#              uses: dawidd6/action-delete-branch@v2.0.1
#              with:
#                  github_token: ${{ secrets.GITHUB_TOKEN }}
#                  branches: gh-pages
