name: Tests
on: [push, pull_request]
env:
    CI: true

jobs:
    test:
        name: Node ${{ matrix.node }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 15.x]

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Set Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install npm dependencies
              run: yarn # switch to `npm ci` when Node.js 6 support is dropped

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: yarn test-cov

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: ${{matrix.os}}-node-${{ matrix.node }}
                  parallel: true

    finish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
